apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ebs-static
spec:
  accessModes:
  - ReadriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: aws-ebi-csi-driver
    fsType: ext4
    volumeHandle: vol-0323ca486472afe23

