apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:   
  - ReadriteOnce
  capacity:
    storage: 20Gi
  csi:
    drivers: csi.ebs.aws.com
    fsType: ext4
    volumeHandle: vol-0b547173b784b1c72
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  accessModes:   
  - ReadriteOnce
  storageClassName: ""
  volumeName: ebs-static
  resources:
    requests:
      storage: Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    environment: dev
    project: expense
spec:
  nodeSelector:
    topology.Kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
    volummeMounts:
    - name: ebs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-static
    persistentVolumeClaim: 
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
  labels:
    environment: dev
    project: expense
spec:
  selector:
    environment: dev
    project: expense
  ports:
  - name: ebs-static
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 

