apiVersion: v1
kind: Pod
metadata: 
  name: expense
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
    module: backend
spec:
  selector:
    labels:
    project: expense
    environment: dev
    module: backend
ports:
- name: services
  protocol: TCP
  port: 80
  targetPort: 80 