apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
    module: backend
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100Mi
        memory: 100M
      limits:
        cpu: 120Mi
        memory: 120M
