apiVersion: v1
kind: PersistentVolume
metadata:
  name: expensepv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0119ab5a8fd8ac930