apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: expense
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: port
    protocol: TCP
    port: 80
    targetPort: 80