apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations:
    project: expense
    environment: dev
    module: backend
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: nginx-config
