apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: expense
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  replicas: 3
  selector: 
    matchLabels:
    project: expense
    environment: dev
    module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        module: backend
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: expense
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  type: LoadBalancer
  selector:
    labels:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: services
    protocol: TCP
    port: 80
    targetPort: 80 