apiVersion: apps/v1
kind: Deployment
metadata:
  name: sets
  labels:
    project: expense
    environment: dev
    module: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      environment: dev
      module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        module: backend
    spec:
      containers:
      - name: nginx
        image: nginx

