apiVersion: v1
kind: Pod
metadata: 
  name: expense
  annotations: 
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100M
        memory: 100Mi
      limits:
        cpu: 120M
        memory: 120Mi      