apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0119ab5a8fd8ac930
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: ebs-static
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:   
  name: volumespod
  labels:
    project: expense
spec:
  nodeSelector:
  topology.kubernetes.io/zone: us-east-1d
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: ebs-static
        mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-static
    persistentVolumeClaim: 
      claimName: ebs-static
