apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    project: expense
    environment: dev
    module: backend

  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80