apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: set
  labels: 
    env: prod
    project: expense
spec:
  replicas: 3
  selector: 
    matchLabels:
        env: prod
        project: expense  

  template: 
    metadata: 
      labels:
        env: prod
        project: expense 
    spec:
      containers:
      - name: nginx
        image: nginx 

---
apiVersion: v1
kind: LoadBalancer
metadata:
  name: service
  labels:
    env: prod
    project: expense 

spec:
  selector:
    matchLabels:
     env: prod
     project: expense    

ports:
- name: name
  protocol: TCP
  port: 80
  targetPort: 80