apiVersion: apps/V1
kind: ReplicaSet
metadata: 
  name: sets
  labels:
    environment: dev
    project: expense
spec:
  selector:   
    matchLabels:
      environment: dev
      project: expense

  template: 
    metadata:   
      lebels:  
        environment: dev
        project: expense 
  spec:
    containers:
    - name: nginx
      image: nginx