apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: set
  labels: 
    env: prod
    project: expense
spec:
  replicas: 3
  selector: 
    matchLabels:
      labels:
        env: prod
        project: expense  

  template: 
    metadata: 
      labels:
        env: prod
        project: expense 
    spec:
      containers:
      - name: nginx
        image: nginx 