apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
   project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: devops
    resources:
      requests:
        cpu: 100m
        memory: 80 Mi
      limits: 
        cpu: 120m
        memory: 120 Mi