apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    project: espense
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep","100"]