apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
   project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100M
        memory: 80Mi
      limits: 
        cpu: 120M
        memory: 120Mi