apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 60Mi
        limits:
          cpu: 120m
          memory: 120Mi