apiVersion: v1
kind: Pod
metadata:
  name: config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course

