apiVersion: v1
kind: pod
metadata:
  name: expense
spec:
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80