apiVersion: v1
kind: Pod
metadata:   
  name: expense
  annotations: 
    project: dev
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux
      command: ["sleep", "100"]