apiVersion: v1
kind: Pod
metadata:
  name: nginx-config
  labels:
    comp: back
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    environment: dev
spec:
  selector:
    comp: back
  ports:
  - name: port
    protocol: TCP
    port: 80
    targetPort: 80


