apiVersion: v1
kind: Service
metadata:
  name: expense
  labels:
    environment: dev
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: svc
    protocol: TCP
    port: 80
    targetPort: 80