apiVersion: v1
kind: Pod
metadata:
  name: multi-pods
  labels:
    component: backend
  namespace: expense
  annotations:
    build_url: something
spec:
  containers:
  - name: nginx
    image: nginx
