apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    compo: back
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: LoadBalancer
  selector:
    compo: back
  ports:
  - name: name
    port: 80
    targetPort: 80
    nodePort: 30001
    