apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    comp: back
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svcc
spec:
  type: nodePort
  selector:
    comp: back
  ports:
  - name: map
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001