apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset
  labels:
    comp: back
spec:
  replicas: 2
  selector:
    matchLabels:
      comp: back
  template:
    metadata:
      labels:
        comp: back
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels: 
    dev: dev
spec:
  selector:
    comp: labels
  ports:
  - name: sc-port
    port: 80
    targetPort: 80
  